# Generated by Django 5.2.16 on 2026-09-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('is_stable', models.BooleanField(default=True)),
                ('office_address', models.CharField(max_length=100)),
                ('profit', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
