# Generated by Django 5.2.16 on 2026-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('course', models.TextField(blank=True)),
                ('isStudy', models.BooleanField(default=True)),
            ],
        ),
    ]
