# Generated by Django 5.2.16 on 2026-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('isWorking', models.BooleanField(default=True)),
                ('salary', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
