# Generated by Django 5.2.16 on 2026-10-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
