# Generated by Django 5.2.16 on 2026-10-04 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_banks_employer'),
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employers'),
        ),
    ]
