# Generated by Django 5.2.16 on 2026-09-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('profession', models.TextField(blank=True)),
            ],
        ),
    ]
