# Generated by Django 5.2.16 on 2026-10-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_descriptions',
            field=models.CharField(default=100),
        ),
    ]
