# Generated by Django 5.2.16 on 2026-10-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_item_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Value',
            new_name='value',
        ),
    ]
